### ISSUE TITLE
hreflang tags generated per page

### ISSUE THREAD

**Issue by kelenakamura** [datocms/nextjs-demo-i18n#4]
https://moz.com/learn/seo/hreflang-tag

```
<link rel="alternate" href="http://example.com" hreflang="es-es" />
<link rel="alternate" href="http://example.com/fr/" hreflang="fr-fr" />
<link rel="alternate" href="http://example.com/pt/" hreflang="pt-pt" />
```

**Comment by matjack1** [comment]
This is a good idea, we are open to accepting PRs. But we are not going to get this project in a production-ready state. It's just a simple demo to show how the multilingual approach can be implemented with DatoCMS and NextJS.
